:toc: preamble

= User-defined `clippy`-like structured code annotations.

(n) a marginal note or explanatory comment made by a scholiast.

== Introduction

There's multiple situations, when automatic reporting is not possible.
In these cases, developers tend to use various TODO comments like `TODO`, `REVIEW`,
`HACKME`, `XXX` and so on.

There's methods to extract and highlight existing TODOs, but all of them work
differently, as a comment doesn't tell exactly, where TODO should be finished
and in which cases it should be continued.

On the other hand `scholium::mark` annotation replaces all kinds of TODOs with
Rust-native way, allowing developers to categorize them with better precision,
write better reasoning and make them easy to extract, report and maintain in the long run.
Thanks to Rust literal string boundaries, it's possible to write long multiline reasons,
for example allowing to attach even code snippets if needed.

Annotation is made to be attached to an exact place and it provides only documentation
value without altering an item attached in any way. This means if the annotation
when be attached to a function, module, crate (or a statement), it documents this
particular item and nothing else.

== Code example

[source,rust]
-----
//! Utility functions for starship launching.
// wait for 54726 for this to work
// #![scholium::mark(doc::misleading, reason = "Module purpose was changed")]

/// Add two numbers.
#[scholium::mark(
    doc::missing_examples,
    reason = "Function documentation doesn't contain examples"
)]
#[scholium::mark(warning, test::missing, reason = "Function missing tests")]
#[scholium::mark(
    info,
    implementation::extend,
    doc::possible_extensions,
    reason = "Extend functionality to use any type implementing `+` operation"
)]
#[scholium::mark(
    third_party::missing_rust_feature,
    reason = "place scholium::mark in inner context",
    see_also = "https://github.com/rust-lang/rust/issues/54726"
)]
fn add(a: u32, b: u32) -> u32 {
   // wait for 54726 for this to work
   // #[scholium::mark(
   //       trace,
   //       int:check-missing,
   //       reason = "Use checked addition whether overflow is the case"
   // )]
   a + b
}
-----

For the example above following information will be reported by a companion tool:

* (after 54726) module (exact) with category `doc::misleading`, reason `Module purpose was changed` with default severity.
* function `add` with category `doc::missing_examples`, reason `Function documentation doesn't contain examples` with default severity.
* function `add` with category `test::missing`, reason `Function missing tests` with `warning` severity.
* function `add` with category `implementation::extend`, reason `Extend functionality to use any type implementing `+` operation` with `info` severity.
* function `add` with category `doc::possible_extensions`, reason `Extend functionality to use any type implementing `+` operation` with `info` severity.
* function `add` with category `third_party::missing_rust_feature`, see-also "https://github.com/rust-lang/rust/issues/54726" and reason "place scholium::mark in inner context", with default severity.
* (after 54726) sentence `a+b` with category `int:check-missing`, reason `Use better addition if overflow is the case` with `debug` severity.


== Basic usage

* List project-local reports ids and their titles with `cargo scholium list`
* Explain project-local reports ids (clippy-like) with `cargo scholium explain <report_id>`
* Collect and report `scholium::mark` attributes from code with `cargo scholium report`

*Example output:*

[source]
-----
 INFO Future implementation
  --> src/file.rs:90:18
  = reason: user defined reason
  = info: Implement in the future
  = help: for further information run `cargo scholium explain group::future_imp`
-----

== Configuration

=== Known reports

Known report ids are located in project under `.config/scholium` folder.
All definitions are located in TOML files and look like below. Filename without
  extension is treated as a group identifier.

*Example report id definition:*

Configuration below will define `group::future_imp` if put in
  `.config/scholium/group.toml` inside a project.

[source,toml]
-----
display-name = "Group display name"

[report.future_imp]
severity = "info" # other values: trace, debug, warning, error or suppress
display-name = "Future implementation"
info = "Implement in the future" # information
documentation = """
Non-implemented feature.

# Recommended action

Implement requested feature.
""" # documentation is shown for explain.
-----

=== Profiles

Profiles are pre-defined configuration setup, could be used during an execution.
Profiles are defined in `.config/scholium.toml` file and may have any name.

To specify profile, use `--profile` in CLI or environment variable `CARGO_SCHOLIUM_PROFILE`


*Example profile definition:*

[source,toml]
-----
[profile.example]
format = "human" # Human readable output
detail = "compact" # write compact details
unknown = "trace" # unknown report ids will be reported at `trace` level (by default).
output = "target/.scholium.log" # write whole output to this file. Default is stdout.

[profile.example.overrides]
# all reports for group `third_party` will be reported with `info` level (by default).
"third_party" = "info"
-----

== MSRV

=== `scholium::mark`

MSRV for proc-macro is `1.71`.

=== `cargo scholium`

Minimal MSRV for report tool is `1.86`, as `cargo_metadata` advises.
However transient dependency `cargo-platform` is updated more often and
the latest version may be incompatible.

Use `cargo update cargo-platform@<current-ver> --precise <compatible-ver>` to build it correctly.
