[package]
name = "scholium-core"

description = "scholium::mark attribute parsing"
readme = "cargo-io.md"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
repository.workspace = true
keywords.workspace = true
authors.workspace = true
rust-version = "1.71"

[dependencies]

proc-macro2 = { workspace = true }
syn = { workspace = true, features = [
  "parsing",
  "proc-macro",
  "full",
  "printing",
] }

[dev-dependencies]
rstest = { workspace = true }
assert_matches = { version = "1.5.0" }

[features]
# Preserve information
with-details = []

[package.metadata.docs.rs]
all-features = true
